//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityLayer.Concrete
{
    using System;
    using System.Collections.Generic;
    
    public partial class Case
    {
        public int ID { get; set; }
        public string MONTH { get; set; }
        public Nullable<decimal> AMOUNT { get; set; }
    }
}
