//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryWeb.Models.Entity
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Members
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Members()
        {
            this.Cash_fines = new HashSet<Cash_fines>();
            this.Transactions = new HashSet<Transactions>();
        }
    
        public int ID { get; set; }
        [Required(ErrorMessage ="Adýnýzý boþ býrakamazsýnýz!")]
        [StringLength(30,ErrorMessage ="30 karakterden fazla giremezsiniz!")]
        public string NAME { get; set; }
        [Required(ErrorMessage = "Soyadýnýzý boþ býrakamazsýnýz!")]
        [StringLength(25, ErrorMessage = "25 karakterden fazla giremezsiniz!")]
        public string SURNAME { get; set; }
        public string MAIL { get; set; }
        public string USERNAME { get; set; }
        [Required(ErrorMessage = "Þifrenizi boþ býrakamazsýnýz!")]
        [StringLength(20, ErrorMessage = "Þifreniz 20 karakterden uzun olamaz!")]
        public string PASSWORD { get; set; }
        public string PHOTO { get; set; }
        public string PHONENUMBER { get; set; }
        public string SCHOOL { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cash_fines> Cash_fines { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Transactions> Transactions { get; set; }
    }
}
