//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryWeb.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Messages
    {
        public int ID { get; set; }
        public string SENDER { get; set; }
        public string RECEIVER { get; set; }
        public string SUBJECT { get; set; }
        public string CONTENT_ { get; set; }
        public Nullable<System.DateTime> DATE_ { get; set; }
    }
}
