//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryWeb.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transactions
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Transactions()
        {
            this.Cash_fines = new HashSet<Cash_fines>();
        }
    
        public int ID { get; set; }
        public Nullable<int> BOOK { get; set; }
        public Nullable<int> MEMBER { get; set; }
        public Nullable<byte> PERSONNEL { get; set; }
        public Nullable<System.DateTime> PURCHASEDATE { get; set; }
        public Nullable<System.DateTime> RETURNDATE { get; set; }
        public Nullable<bool> PROCCESS_CASE { get; set; }
        public Nullable<System.DateTime> HANDEDDATE { get; set; }
    
        public virtual Books Books { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cash_fines> Cash_fines { get; set; }
        public virtual Members Members { get; set; }
        public virtual Personnels Personnels { get; set; }
    }
}
